(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{};
const state={equipos:[],cuentas:[],clientes:[],revendedores:[],proveedores:[],texto:"",estado:"TODOS",tipoVendedor:"TODOS",editandoCuenta:"",editandoEquipo:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const E={menu:$("#menuLateral"),capa:$("#capaOscura"),abrir:$("#botonAbrirMenu"),cerrar:$("#botonCerrarMenu"),salir:$("#botonCerrarSesion"),actualizar:$("#botonActualizar"),conexion:$("#estadoConexion"),mensaje:$("#mensajePanel"),contador:$("#contadorAlertas"),nuevoEquipo:$("#botonNuevoEquipo"),nuevaCuenta:$("#botonNuevaCuenta"),rejillaEquipos:$("#rejillaEquipos"),tabla:$("#tablaCanvaBody"),cargando:$("#cargandoCanva"),vacio:$("#estadoVacio"),buscar:$("#buscarCuenta"),filtroEstado:$("#filtroEstado"),filtroTipo:$("#filtroTipoVenta"),kEquipos:$("#kpiEquipos"),kActivas:$("#kpiActivas"),kPor:$("#kpiPorVencer"),kCupos:$("#kpiCupos"),modalEquipo:$("#modalEquipo"),cerrarEquipo:$("#botonCerrarEquipo"),cancelarEquipo:$("#botonCancelarEquipo"),formEquipo:$("#formularioEquipo"),tituloEquipo:$("#tituloModalEquipo"),guardarEquipo:$("#botonGuardarEquipo"),modalCuenta:$("#modalCuenta"),cerrarCuenta:$("#botonCerrarCuenta"),cancelarCuenta:$("#botonCancelarCuenta"),formCuenta:$("#formularioCuenta"),tituloCuenta:$("#tituloModalCuenta"),guardarCuenta:$("#botonGuardarCuenta"),modalDetalle:$("#modalDetalle"),cerrarDetalle:$("#botonCerrarDetalle"),tituloDetalle:$("#tituloDetalle"),contenidoDetalle:$("#contenidoDetalle")};
const CE={nombre:$("#equipoNombre"),capacidad:$("#equipoCapacidad"),estado:$("#equipoEstado"),correo:$("#equipoCorreo"),proveedorId:$("#equipoProveedorId"),notas:$("#equipoNotas")};
const CC=["clienteId","nombreCompleto","whatsapp","correoCanva","equipoId","tipoOperacion","tiempoMeses","fechaCompra","fechaVencimiento","estado","tipoVendedor","revendedorId","precio","moneda","estadoPago","notas"].reduce((o,id)=>(o[id]=$("#"+id),o),{});
const mensajeCupos=$("#mensajeCupos");

function msg(t,tipo="exito"){E.mensaje.textContent=t;E.mensaje.className=`mensaje-flotante visible ${tipo}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje-flotante",4200)}
async function get(action,extra={}){if(!cfg.APPS_SCRIPT_URL||!cfg.API_KEY_SOCIOS)throw Error("Falta configurar la conexión.");const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action",action);u.searchParams.set("claveApi",cfg.API_KEY_SOCIOS);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function post(body){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...body,claveApi:cfg.API_KEY_SOCIOS})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}

async function cargar(){
  E.cargando.hidden=false;E.vacio.hidden=true;E.tabla.innerHTML="";
  try{
    const [eq,cu,cl,re,pr]=await Promise.all([get("listarEquiposCanva"),get("listarCuentasCanva"),get("listarClientes"),get("listarSocios",{tipo:"REVENDEDOR"}),get("listarSocios",{tipo:"PROVEEDOR"})]);
    state.equipos=eq.registros||[];state.cuentas=cu.registros||[];state.clientes=(cl.registros||[]).filter(x=>x.estado==="ACTIVO");state.revendedores=re.registros||[];state.proveedores=pr.registros||[];
    llenarSelects();render();
    E.conexion.textContent="Google Sheets conectado";E.conexion.className="estado-conexion conectado";
  }catch(e){E.cargando.hidden=true;E.vacio.hidden=false;E.conexion.textContent="Sin conexión";msg(e.message,"error")}
}

function llenarSelects(){
  CE.proveedorId.innerHTML='<option value="">Sin proveedor interno</option>'+state.proveedores.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} ${esc(x.apellido||"")}</option>`).join("");
  CC.clienteId.innerHTML='<option value="">Cliente manual</option>'+state.clientes.map(x=>`<option value="${esc(x.id)}">${esc(x.nombreCompleto)} · +${esc(x.telefono)}</option>`).join("");
  CC.equipoId.innerHTML='<option value="">Selecciona un equipo</option>'+state.equipos.filter(x=>x.estado==="ACTIVO").map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} · ${x.disponibles} cupo(s)</option>`).join("");
  CC.revendedorId.innerHTML='<option value="">Selecciona un revendedor</option>'+state.revendedores.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} ${esc(x.apellido||"")}</option>`).join("");
}

function filtradas(){const t=state.texto.toLowerCase();return state.cuentas.filter(c=>(state.estado==="TODOS"||c.estado===state.estado)&&(state.tipoVendedor==="TODOS"||c.tipoVendedor===state.tipoVendedor)&&(!t||[c.nombreCompleto,c.whatsapp,c.correoCanva,c.equipoNombre,c.vendedorNombre].join(" ").toLowerCase().includes(t)))}
function render(){renderEquipos();const l=filtradas();E.cargando.hidden=true;E.vacio.hidden=!!l.length;E.tabla.innerHTML=l.map(row).join("");kpis();$$("[data-a-canva]").forEach(b=>b.onclick=()=>accionCuenta(b.dataset.aCanva,b.dataset.id));$$("[data-equipo-editar]").forEach(b=>b.onclick=()=>abrirEquipo(state.equipos.find(x=>x.id===b.dataset.equipoEditar)))}
function renderEquipos(){E.rejillaEquipos.innerHTML=state.equipos.map(e=>{const uso=e.capacidad?Math.min(100,Math.round((e.ocupados/e.capacidad)*100)):0;return `<article class="tarjeta-equipo-canva"><div class="cabecera"><div><h4>${esc(e.nombre)}</h4><small>${esc(e.correoAdministrador||"Sin correo administrador")}</small></div><span class="estado-canva ${e.estado==="ACTIVO"?"activa":"cortada"}">${esc(e.estado)}</span></div><div class="barra-cupos"><span style="width:${uso}%"></span></div><div class="datos-cupos"><span>Ocupados: <strong>${e.ocupados}</strong></span><span>Disponibles: <strong>${e.disponibles}</strong></span><span>Total: <strong>${e.capacidad}</strong></span></div><div class="acciones-equipo"><button data-equipo-editar="${esc(e.id)}" title="Editar equipo"><svg><use href="#i-edit"></use></svg></button></div></article>`}).join("")}
function row(c){return `<tr><td><div class="celda-canva"><strong>${esc(c.nombreCompleto)}</strong><small>+${esc(c.whatsapp)}</small></div></td><td><div class="celda-canva"><strong>${esc(c.correoCanva)}</strong><small>${esc(c.clienteId||"Cliente manual")}</small></div></td><td><div class="celda-canva"><strong>${esc(c.equipoNombre)}</strong><small>${c.equipoDisponibles} cupo(s) libres</small></div></td><td>${fecha(c.fechaCompra)}</td><td>${fecha(c.fechaVencimiento)}</td><td>${c.tiempoMeses} mes(es)</td><td>${esc(c.tipoOperacion)}</td><td><div class="celda-canva"><strong>${esc(c.tipoVendedor)}</strong><small>${esc(c.vendedorNombre||"Administrador")}</small></div></td><td><span class="estado-canva ${c.estado.toLowerCase()}">${esc(c.estado)}</span></td><td><div class="acciones-canva"><button data-a-canva="ver" data-id="${c.id}" title="Ver"><svg><use href="#i-eye"></use></svg></button><button data-a-canva="editar" data-id="${c.id}" title="Editar"><svg><use href="#i-edit"></use></svg></button><button class="whatsapp" data-a-canva="whatsapp" data-id="${c.id}" title="Mensaje al cliente"><svg><use href="#i-whatsapp"></use></svg></button></div></td></tr>`}

function accionCuenta(a,id){const c=state.cuentas.find(x=>x.id===id);if(!c)return;if(a==="ver")verDetalle(c);if(a==="editar")abrirCuenta(c);if(a==="whatsapp")abrirWhatsapp(c)}
function abrirWhatsapp(c){const num=String(c.whatsapp||"").replace(/\D/g,"");if(!num)return msg("El cliente no tiene WhatsApp.","error");const texto=`Hola ${c.nombreCompleto} 👋\n\nTu cuenta de Canva está registrada con la siguiente información:\n\nCorreo: ${c.correoCanva}\nEquipo: ${c.equipoNombre}\nFecha de compra: ${fecha(c.fechaCompra)}\nFecha de vencimiento: ${fecha(c.fechaVencimiento)}\nTiempo contratado: ${c.tiempoMeses} mes(es)\nEstado: ${c.estado}\n\nGracias por confiar en Mundo Digital 2.0.`;window.open(`https://wa.me/${num}?text=${encodeURIComponent(texto)}`,"_blank","noopener")}
function abrirEquipo(e=null){state.editandoEquipo=e?.id||"";E.formEquipo.reset();CE.capacidad.value=500;CE.estado.value="ACTIVO";E.tituloEquipo.textContent=e?"Editar equipo":"Nuevo equipo";if(e){CE.nombre.value=e.nombre;CE.capacidad.value=e.capacidad;CE.estado.value=e.estado;CE.correo.value=e.correoAdministrador||"";CE.proveedorId.value=e.proveedorId||"";CE.notas.value=e.notas||""}E.modalEquipo.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarEquipo(){E.modalEquipo.classList.remove("visible");document.body.style.overflow="";state.editandoEquipo=""}
async function guardarEquipo(ev){ev.preventDefault();if(!CE.nombre.value.trim()||Number(CE.capacidad.value||0)<1)return msg("Nombre y capacidad son obligatorios.","error");E.guardarEquipo.disabled=true;E.guardarEquipo.textContent="Guardando...";try{await post({action:"guardarEquipoCanva",registro:{id:state.editandoEquipo,nombre:CE.nombre.value.trim(),capacidad:Number(CE.capacidad.value),estado:CE.estado.value,correoAdministrador:CE.correo.value.trim(),proveedorId:CE.proveedorId.value,notas:CE.notas.value.trim()}});cerrarEquipo();msg("Equipo de Canva guardado.");await cargar()}catch(e){msg(e.message,"error")}finally{E.guardarEquipo.disabled=false;E.guardarEquipo.textContent="Guardar equipo"}}
function abrirCuenta(c=null){state.editandoCuenta=c?.id||"";E.formCuenta.reset();CC.fechaCompra.value=hoy();CC.tiempoMeses.value="1";CC.tipoOperacion.value="NUEVO";CC.tipoVendedor.value="ADMIN";CC.precio.value=0;CC.moneda.value="USD";CC.estadoPago.value="PENDIENTE";CC.estado.value="ACTIVA";E.tituloCuenta.textContent=c?"Editar cuenta Canva":"Nueva cuenta Canva";if(c)Object.keys(CC).forEach(k=>{if(c[k]!=null)CC[k].value=c[k]});actualizarVencimiento();actualizarCupos();actualizarRevendedor();E.modalCuenta.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarCuenta(){E.modalCuenta.classList.remove("visible");document.body.style.overflow="";state.editandoCuenta=""}
function aplicarCliente(){const c=state.clientes.find(x=>x.id===CC.clienteId.value);if(!c)return;CC.nombreCompleto.value=c.nombreCompleto||"";CC.whatsapp.value=c.telefono||"";if(!CC.correoCanva.value)CC.correoCanva.value=c.correo||""}
function actualizarVencimiento(){if(!CC.fechaCompra.value)return CC.fechaVencimiento.value="";const d=new Date(CC.fechaCompra.value+"T00:00:00"),dias=Number(CC.tiempoMeses.value||1)*30;d.setDate(d.getDate()+dias);CC.fechaVencimiento.value=d.toISOString().slice(0,10)}
function actualizarCupos(){const e=state.equipos.find(x=>x.id===CC.equipoId.value);if(!e){mensajeCupos.textContent="Selecciona un equipo para consultar sus cupos.";mensajeCupos.className="ayuda-campo-canva";return}mensajeCupos.textContent=`Capacidad: ${e.capacidad} · Ocupados: ${e.ocupados} · Disponibles: ${e.disponibles}`;mensajeCupos.className=`ayuda-campo-canva ${e.disponibles>0?"disponible":"lleno"}`}
function actualizarRevendedor(){const esRev=CC.tipoVendedor.value==="REVENDEDOR";CC.revendedorId.disabled=!esRev;if(!esRev)CC.revendedorId.value=""}
async function guardarCuenta(ev){ev.preventDefault();if(!CC.nombreCompleto.value.trim()||!CC.whatsapp.value.trim()||!CC.correoCanva.value.trim()||!CC.equipoId.value)return msg("Nombre, WhatsApp, correo y equipo son obligatorios.","error");if(CC.tipoVendedor.value==="REVENDEDOR"&&!CC.revendedorId.value)return msg("Selecciona el revendedor.","error");E.guardarCuenta.disabled=true;E.guardarCuenta.textContent="Guardando...";const r={id:state.editandoCuenta};Object.keys(CC).forEach(k=>r[k]=CC[k].value);try{await post({action:"guardarCuentaCanva",registro:r});cerrarCuenta();msg("Cuenta Canva guardada correctamente.");await cargar()}catch(e){msg(e.message,"error")}finally{E.guardarCuenta.disabled=false;E.guardarCuenta.textContent="Guardar cuenta Canva"}}
function verDetalle(c){E.tituloDetalle.textContent=`${c.nombreCompleto} · Canva`;E.contenidoDetalle.innerHTML=`<div class="detalle-grid-canva"><div class="detalle-item-canva"><span>Cliente</span><strong>${esc(c.nombreCompleto)}</strong></div><div class="detalle-item-canva"><span>WhatsApp</span><strong>+${esc(c.whatsapp)}</strong></div><div class="detalle-item-canva"><span>Correo Canva</span><strong>${esc(c.correoCanva)}</strong></div><div class="detalle-item-canva"><span>Equipo</span><strong>${esc(c.equipoNombre)}</strong></div><div class="detalle-item-canva"><span>Fecha de compra</span><strong>${fecha(c.fechaCompra)}</strong></div><div class="detalle-item-canva"><span>Fecha de vencimiento</span><strong>${fecha(c.fechaVencimiento)}</strong></div><div class="detalle-item-canva"><span>Tiempo</span><strong>${c.tiempoMeses} mes(es) · ${c.tiempoMeses*30} días</strong></div><div class="detalle-item-canva"><span>Operación</span><strong>${esc(c.tipoOperacion)}</strong></div><div class="detalle-item-canva"><span>Vendido por</span><strong>${esc(c.tipoVendedor)} · ${esc(c.vendedorNombre||"Administrador")}</strong></div><div class="detalle-item-canva"><span>Precio</span><strong>${money(c.precio)} ${esc(c.moneda)}</strong></div><div class="detalle-item-canva"><span>Pago</span><strong>${esc(c.estadoPago)}</strong></div><div class="detalle-item-canva"><span>Estado</span><strong>${esc(c.estado)}</strong></div><div class="detalle-item-canva ancho"><span>Notas</span><strong>${esc(c.notas||"Sin notas")}</strong></div></div>`;E.modalDetalle.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarDetalle(){E.modalDetalle.classList.remove("visible");document.body.style.overflow=""}
function kpis(){const activosEquipos=state.equipos.filter(e=>e.estado==="ACTIVO").length,activas=state.cuentas.filter(c=>c.estado==="ACTIVA").length,por=state.cuentas.filter(c=>c.estado==="POR_VENCER").length,cupos=state.equipos.reduce((s,e)=>s+Number(e.disponibles||0),0);E.kEquipos.textContent=activosEquipos;E.kActivas.textContent=activas;E.kPor.textContent=por;E.kCupos.textContent=cupos;E.contador.textContent=por+state.cuentas.filter(c=>c.estado==="VENCIDA").length}
const hoy=()=>new Date().toISOString().slice(0,10),fecha=v=>v?new Date(v+"T00:00:00").toLocaleDateString("es-ES"):"",money=n=>Number(n||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
E.nuevoEquipo.onclick=()=>abrirEquipo();E.nuevaCuenta.onclick=()=>abrirCuenta();E.cerrarEquipo.onclick=E.cancelarEquipo.onclick=cerrarEquipo;E.modalEquipo.onclick=e=>{if(e.target===E.modalEquipo)cerrarEquipo()};E.formEquipo.onsubmit=guardarEquipo;E.cerrarCuenta.onclick=E.cancelarCuenta.onclick=cerrarCuenta;E.modalCuenta.onclick=e=>{if(e.target===E.modalCuenta)cerrarCuenta()};E.formCuenta.onsubmit=guardarCuenta;E.cerrarDetalle.onclick=cerrarDetalle;E.modalDetalle.onclick=e=>{if(e.target===E.modalDetalle)cerrarDetalle()};CC.clienteId.onchange=aplicarCliente;CC.equipoId.onchange=actualizarCupos;CC.fechaCompra.onchange=actualizarVencimiento;CC.tiempoMeses.onchange=actualizarVencimiento;CC.tipoVendedor.onchange=actualizarRevendedor;E.buscar.oninput=()=>{state.texto=E.buscar.value.trim();render()};E.filtroEstado.onchange=()=>{state.estado=E.filtroEstado.value;render()};E.filtroTipo.onchange=()=>{state.tipoVendedor=E.filtroTipo.value;render()};E.actualizar.onclick=cargar;E.abrir.onclick=()=>{E.menu.classList.add("abierto");E.capa.classList.add("visible")};E.cerrar.onclick=()=>{E.menu.classList.remove("abierto");E.capa.classList.remove("visible")};E.capa.onclick=()=>E.cerrar.click();E.salir.onclick=()=>{if(confirm("¿Cerrar sesión?"))location.href="index.html"};$$("[data-pagina]").forEach(a=>a.onclick=e=>{e.preventDefault();msg(`La sección ${a.dataset.pagina} se creará después.`,"informacion")});cargar();
})();