(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{},state={cuentas:[],productos:[],proveedores:[],texto:"",estado:"TODOS",tipo:"TODOS",editando:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const E={menu:$("#menuLateral"),capa:$("#capaOscura"),abrir:$("#botonAbrirMenu"),cerrar:$("#botonCerrarMenu"),salir:$("#botonCerrarSesion"),actualizar:$("#botonActualizar"),conexion:$("#estadoConexion"),mensaje:$("#mensajePanel"),nueva:$("#botonNuevaCuenta"),modal:$("#modalCuenta"),cerrarModal:$("#botonCerrarModal"),cancelar:$("#botonCancelar"),form:$("#formularioCuenta"),titulo:$("#tituloModal"),guardar:$("#botonGuardar"),tabla:$("#tablaInventarioBody"),cargando:$("#cargandoInventario"),vacio:$("#estadoVacio"),buscar:$("#buscarCuenta"),filtroEstado:$("#filtroEstado"),filtroTipo:$("#filtroTipo"),kTotal:$("#kpiTotal"),kDisp:$("#kpiDisponibles"),kCupos:$("#kpiCupos"),kPor:$("#kpiPorVencer"),modalDetalle:$("#modalDetalle"),cerrarDetalle:$("#botonCerrarDetalle"),tituloDetalle:$("#tituloDetalle"),contenidoDetalle:$("#contenidoDetalle")};
const ids=["productoId","proveedorId","plataforma","tipoCuenta","usuarioCuenta","contrasenaCuenta","correoRecuperacion","telefonoRecuperacion","perfil","pin","pantallasTotales","pantallasDisponibles","fechaCompra","fechaVencimiento","costo","moneda","estado","notas"];
const C=ids.reduce((o,id)=>(o[id]=$("#"+id),o),{});
function msg(t,tipo="exito"){E.mensaje.textContent=t;E.mensaje.className=`mensaje-flotante visible ${tipo}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje-flotante",4000)}
async function get(action,extra={}){const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action",action);u.searchParams.set("claveApi",cfg.API_KEY_SOCIOS);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function post(body){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...body,claveApi:cfg.API_KEY_SOCIOS})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function cargar(){E.cargando.hidden=false;E.vacio.hidden=true;E.tabla.innerHTML="";try{const [cu,p,pr]=await Promise.all([get("listarInventarioDigital"),get("listarProductos"),get("listarSocios",{tipo:"PROVEEDOR"})]);state.cuentas=cu.registros||[];state.productos=(p.registros||[]).filter(x=>x.estado==="ACTIVO");state.proveedores=pr.registros||[];llenar();render();E.conexion.textContent="Google Sheets conectado";E.conexion.className="estado-conexion conectado"}catch(e){E.cargando.hidden=true;E.vacio.hidden=false;E.conexion.textContent="Sin conexión";msg(e.message,"error")}}
function llenar(){C.productoId.innerHTML='<option value="">Selecciona un producto</option>'+state.productos.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)}</option>`).join("");C.proveedorId.innerHTML='<option value="">Sin proveedor</option>'+state.proveedores.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} ${esc(x.apellido||"")}</option>`).join("")}
function filtradas(){const t=state.texto.toLowerCase();return state.cuentas.filter(c=>(state.estado==="TODOS"||c.estado===state.estado)&&(state.tipo==="TODOS"||c.tipoCuenta===state.tipo)&&(!t||[c.productoNombre,c.plataforma,c.usuarioCuenta,c.proveedorNombre].join(" ").toLowerCase().includes(t)))}
function render(){const l=filtradas();E.cargando.hidden=true;E.vacio.hidden=!!l.length;E.tabla.innerHTML=l.map(row).join("");kpis();$$("[data-inv]").forEach(b=>b.onclick=()=>accion(b.dataset.inv,b.dataset.id))}
function row(c){return `<tr><td><div class="celda-inv"><strong>${esc(c.productoNombre||c.plataforma)}</strong><small>${esc(c.plataforma)}</small></div></td><td><div class="celda-inv"><strong>${esc(c.usuarioCuenta)}</strong><small>${esc(c.perfil||"Sin perfil")}</small></div></td><td>${esc(c.tipoCuenta)}</td><td><div class="cupos-inv"><strong>${Number(c.pantallasDisponibles||0)}</strong><small>de ${Number(c.pantallasTotales||0)}</small></div></td><td><div class="celda-inv"><strong>${esc(c.proveedorNombre||"Sin proveedor")}</strong><small>Solo administrador</small></div></td><td>${fecha(c.fechaCompra)}</td><td>${fecha(c.fechaVencimiento)}<br><small>${Number(c.diasRestantes||0)} día(s)</small></td><td>${money(c.costo)} ${esc(c.moneda)}</td><td><span class="estado-inv ${c.estado.toLowerCase()}">${esc(c.estado)}</span></td><td><div class="acciones-inv"><button data-inv="ver" data-id="${c.id}"><svg><use href="#i-eye"></use></svg></button><button data-inv="editar" data-id="${c.id}"><svg><use href="#i-edit"></use></svg></button></div></td></tr>`}
function accion(a,id){const c=state.cuentas.find(x=>x.id===id);if(!c)return;if(a==="ver")ver(c);if(a==="editar")abrirModal(c)}
function abrirModal(c=null){state.editando=c?.id||"";E.form.reset();C.pantallasTotales.value=1;C.pantallasDisponibles.value=1;C.costo.value=0;C.moneda.value="USD";C.estado.value="DISPONIBLE";C.tipoCuenta.value="CUENTA_COMPLETA";C.fechaCompra.value=new Date().toISOString().slice(0,10);E.titulo.textContent=c?"Editar cuenta":"Nueva cuenta";if(c)ids.forEach(id=>{if(c[id]!=null)C[id].value=c[id]});E.modal.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarModal(){E.modal.classList.remove("visible");document.body.style.overflow="";state.editando=""}
async function guardar(ev){ev.preventDefault();if(!C.productoId.value||!C.usuarioCuenta.value.trim())return msg("Producto y usuario son obligatorios.","error");if(Number(C.pantallasDisponibles.value)>Number(C.pantallasTotales.value))return msg("Los cupos disponibles no pueden superar el total.","error");const r={id:state.editando};ids.forEach(id=>r[id]=C[id].value);E.guardar.disabled=true;E.guardar.textContent="Guardando...";try{await post({action:"guardarInventarioDigital",registro:r});cerrarModal();msg("Cuenta guardada correctamente.");await cargar()}catch(e){msg(e.message,"error")}finally{E.guardar.disabled=false;E.guardar.textContent="Guardar cuenta"}}
function ver(c){E.tituloDetalle.textContent=`${c.productoNombre} · ${c.usuarioCuenta}`;E.contenidoDetalle.innerHTML=`<div class="detalle-grid-inv"><div class="detalle-item-inv"><span>Producto</span><strong>${esc(c.productoNombre)}</strong></div><div class="detalle-item-inv"><span>Proveedor privado</span><strong>${esc(c.proveedorNombre||"Sin proveedor")}</strong></div><div class="detalle-item-inv"><span>Usuario</span><strong>${esc(c.usuarioCuenta)}</strong></div><div class="detalle-item-inv"><span>Contraseña</span><strong>${esc(c.contrasenaCuenta||"")}</strong></div><div class="detalle-item-inv"><span>Perfil</span><strong>${esc(c.perfil||"")}</strong></div><div class="detalle-item-inv"><span>PIN</span><strong>${esc(c.pin||"")}</strong></div><div class="detalle-item-inv"><span>Cupos</span><strong>${c.pantallasDisponibles} de ${c.pantallasTotales}</strong></div><div class="detalle-item-inv"><span>Vencimiento</span><strong>${fecha(c.fechaVencimiento)}</strong></div><div class="detalle-item-inv"><span>Costo</span><strong>${money(c.costo)} ${esc(c.moneda)}</strong></div><div class="detalle-item-inv"><span>Estado</span><strong>${esc(c.estado)}</strong></div><div class="detalle-item-inv ancho"><span>Notas internas</span><strong>${esc(c.notas||"Sin notas")}</strong></div></div>`;E.modalDetalle.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarDetalle(){E.modalDetalle.classList.remove("visible");document.body.style.overflow=""}
function kpis(){E.kTotal.textContent=state.cuentas.length;E.kDisp.textContent=state.cuentas.filter(c=>c.estado==="DISPONIBLE").length;E.kCupos.textContent=state.cuentas.reduce((s,c)=>s+Number(c.pantallasDisponibles||0),0);E.kPor.textContent=state.cuentas.filter(c=>c.estado==="POR_VENCER").length}
const fecha=v=>v?new Date(v+"T00:00:00").toLocaleDateString("es-ES"):"",money=n=>Number(n||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
E.nueva.onclick=()=>abrirModal();E.cerrarModal.onclick=E.cancelar.onclick=cerrarModal;E.modal.onclick=e=>{if(e.target===E.modal)cerrarModal()};E.form.onsubmit=guardar;E.cerrarDetalle.onclick=cerrarDetalle;E.modalDetalle.onclick=e=>{if(e.target===E.modalDetalle)cerrarDetalle()};E.buscar.oninput=()=>{state.texto=E.buscar.value.trim();render()};E.filtroEstado.onchange=()=>{state.estado=E.filtroEstado.value;render()};E.filtroTipo.onchange=()=>{state.tipo=E.filtroTipo.value;render()};E.actualizar.onclick=cargar;E.abrir.onclick=()=>{E.menu.classList.add("abierto");E.capa.classList.add("visible")};E.cerrar.onclick=()=>{E.menu.classList.remove("abierto");E.capa.classList.remove("visible")};E.capa.onclick=()=>E.cerrar.click();E.salir.onclick=()=>{if(confirm("¿Cerrar sesión?"))location.href="index.html"};cargar();
})();