(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{},token=new URLSearchParams(location.search).get("token")||"";
const $=s=>document.querySelector(s);
const E={cargando:$("#cargandoPortal"),error:$("#errorPortal"),textoError:$("#textoError"),contenido:$("#contenidoPortal"),nombre:$("#nombreCliente"),soporte:$("#botonSoporte"),activos:$("#totalActivos"),por:$("#totalPorVencer"),vencidos:$("#totalVencidos"),lista:$("#listaServicios"),sin:$("#sinServicios"),mensaje:$("#mensajePortal")};
function msg(t,tipo="ok"){E.mensaje.textContent=t;E.mensaje.className=`mensaje visible ${tipo==="error"?"error":""}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje",3800)}
async function getPortal(){if(!token)throw Error("El enlace no contiene un token.");const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action","consultarPortalCliente");u.searchParams.set("token",token);const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"No se pudo abrir el portal.");return d}
async function responder(servicioId,tipoServicio,respuesta){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"responderRenovacionPortal",token,servicioId,tipoServicio,respuesta})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"No se pudo guardar la respuesta.");return d}
function fecha(v){return v?new Date(v+"T00:00:00").toLocaleDateString("es-ES"):"Sin fecha"}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function tarjeta(s){const correo=s.correo||s.usuarioCuenta||"No registrado",equipo=s.equipoNombre||s.plataforma||"",respuesta=s.respuestaCliente||"SIN_RESPUESTA";return `<article class="servicio"><div class="servicio-cabecera"><div><h4>${esc(s.nombre)}</h4><p class="subtitulo">${esc(s.tipoServicio==="CANVA"?"Cuenta de Canva":"Suscripción digital")}</p></div><span class="estado ${String(s.estado).toLowerCase()}">${esc(s.estado)}</span></div><div class="datos"><div class="dato"><span>Correo o usuario</span><strong>${esc(correo)}</strong></div>${equipo?`<div class="dato"><span>${s.tipoServicio==="CANVA"?"Equipo":"Plataforma"}</span><strong>${esc(equipo)}</strong></div>`:""}<div class="dato"><span>Fecha de compra</span><strong>${fecha(s.fechaInicio)}</strong></div><div class="dato"><span>Fecha de vencimiento</span><strong>${fecha(s.fechaVencimiento)}</strong></div><div class="dato"><span>Días restantes</span><strong>${Number(s.diasRestantes||0)}</strong></div><div class="dato"><span>Precio de renovación</span><strong>${Number(s.precioRenovacion||0).toLocaleString("es-ES",{minimumFractionDigits:2})} ${esc(s.moneda||"USD")}</strong></div></div><div class="acciones"><button class="renovar" data-id="${esc(s.id)}" data-tipo="${esc(s.tipoServicio)}" data-respuesta="RENOVAR">Renovar</button><button class="no-renovar" data-id="${esc(s.id)}" data-tipo="${esc(s.tipoServicio)}" data-respuesta="NO_RENOVAR">No renovar</button></div><div class="respuesta">Respuesta actual: <strong>${esc(respuesta)}</strong></div></article>`}
async function cargar(){try{const d=await getPortal(),servicios=d.servicios||[];E.nombre.textContent=d.cliente.nombreCompleto||"cliente";const numero=String(d.soporteWhatsapp||"").replace(/\D/g,"");E.soporte.href=numero?`https://wa.me/${numero}?text=${encodeURIComponent("Hola, necesito ayuda con mis servicios de Mundo Digital 2.0.")}`:"#";E.activos.textContent=servicios.filter(x=>x.estado==="ACTIVA").length;E.por.textContent=servicios.filter(x=>x.estado==="POR_VENCER").length;E.vencidos.textContent=servicios.filter(x=>x.estado==="VENCIDA").length;E.lista.innerHTML=servicios.map(tarjeta).join("");E.sin.hidden=servicios.length>0;E.cargando.hidden=true;E.contenido.hidden=false;document.querySelectorAll("[data-respuesta]").forEach(b=>b.onclick=async()=>{const texto=b.dataset.respuesta==="RENOVAR"?"¿Confirmas que deseas renovar este servicio?":"¿Confirmas que no deseas renovar este servicio?";if(!confirm(texto))return;b.disabled=true;try{await responder(b.dataset.id,b.dataset.tipo,b.dataset.respuesta);msg("Tu respuesta fue registrada correctamente.");await cargar()}catch(e){msg(e.message,"error")}finally{b.disabled=false}})}catch(e){E.cargando.hidden=true;E.error.hidden=false;E.textoError.textContent=e.message}}
cargar();
})();