(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{}, estado={productos:[],categorias:[],editando:"",texto:"",categoria:"TODAS",filtroEstado:"TODOS"};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={menu:$("#menuLateral"),capa:$("#capaOscura"),abrir:$("#botonAbrirMenu"),cerrar:$("#botonCerrarMenu"),salir:$("#botonCerrarSesion"),nuevo:$("#botonNuevoProducto"),modal:$("#modalProducto"),cerrarModal:$("#botonCerrarModal"),cancelar:$("#botonCancelar"),form:$("#formularioProducto"),titulo:$("#tituloModal"),guardar:$("#botonGuardar"),rejilla:$("#rejillaProductos"),cargando:$("#cargandoProductos"),vacio:$("#estadoVacio"),buscar:$("#buscarProducto"),filtroCat:$("#filtroCategoria"),filtroEstado:$("#filtroEstado"),actualizar:$("#botonActualizar"),conexion:$("#estadoConexion"),mensaje:$("#mensajePanel"),kTotal:$("#kpiTotal"),kActivos:$("#kpiActivos"),kStock:$("#kpiStock"),kValor:$("#kpiValor")};
const ids=["nombre","descripcion","categoriaId","tipoProducto","tipoEntrega","precioCompra","precioVenta","moneda","duracionDias","stockMinimo","controlarStock","archivoId","imagenUrl","estado"];
const C=ids.reduce((o,id)=>(o[id]=$("#"+id),o),{});
function msg(t,tipo="exito"){E.mensaje.textContent=t;E.mensaje.className=`mensaje-flotante visible ${tipo}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje-flotante",3800)}
async function get(action){const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action",action);u.searchParams.set("claveApi",cfg.API_KEY_SOCIOS);const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function post(body){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...body,claveApi:cfg.API_KEY_SOCIOS})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function cargar(){E.cargando.hidden=false;E.vacio.hidden=true;E.rejilla.innerHTML="";try{const [p,c]=await Promise.all([get("listarProductos"),get("listarCategorias")]);estado.productos=p.registros||[];estado.categorias=c.registros||[];llenarCategorias();render();E.conexion.textContent="Google Sheets conectado";E.conexion.className="estado-conexion conectado"}catch(e){E.cargando.hidden=true;E.vacio.hidden=false;E.conexion.textContent="Sin conexión";msg(e.message,"error")}}
function llenarCategorias(){const opts=estado.categorias.map(c=>`<option value="${esc(c.id)}">${esc(c.nombre)}</option>`).join("");C.categoriaId.innerHTML=opts;E.filtroCat.innerHTML='<option value="TODAS">Todas las categorías</option>'+opts}
function filtrados(){const t=estado.texto.toLowerCase();return estado.productos.filter(p=>(estado.categoria==="TODAS"||p.categoriaId===estado.categoria)&&(estado.filtroEstado==="TODOS"||p.estado===estado.filtroEstado)&&(!t||[p.nombre,p.descripcion,p.categoriaNombre,p.tipoProducto,p.tipoEntrega].join(" ").toLowerCase().includes(t)))}
function render(){const l=filtrados();E.cargando.hidden=true;E.vacio.hidden=!!l.length;E.rejilla.innerHTML=l.map(card).join("");kpis();$$("[data-a]").forEach(b=>b.onclick=()=>accion(b.dataset.a,b.dataset.id))}
function card(p){const fondo=p.imagenUrl?`style="background-image:linear-gradient(rgba(8,8,10,.18),rgba(8,8,10,.55)),url('${escAttr(p.imagenUrl)}')"`:"";return `<article class="tarjeta-producto"><div class="imagen-producto" ${fondo}>${p.imagenUrl?"":'<svg><use href="#i-box"></use></svg>'}</div><div class="cuerpo-producto"><div class="cabecera-tarjeta-producto"><div><h3>${esc(p.nombre)}</h3><p class="categoria-producto">${esc(p.categoriaNombre||p.categoriaId)}</p></div><span class="badge-producto ${p.estado.toLowerCase()}">${esc(p.estado)}</span></div><p class="descripcion-producto">${esc(p.descripcion||"Sin descripción")}</p><div class="datos-producto"><div class="dato-producto"><span>Entrega</span><strong>${esc(p.tipoEntrega)}</strong></div><div class="dato-producto"><span>Duración</span><strong>${Number(p.duracionDias||0)} días</strong></div><div class="dato-producto"><span>Stock</span><strong>${p.controlarStock==="SI"?"Controlado":"Sin control"}</strong></div><div class="dato-producto"><span>Costo</span><strong>${money(p.precioCompra)} ${esc(p.moneda)}</strong></div></div><div class="pie-producto"><span class="precio-producto">${money(p.precioVenta)} ${esc(p.moneda)}</span><div class="acciones-producto">${p.archivoId?`<button data-a="abrir" data-id="${p.id}" title="Abrir enlace"><svg><use href="#i-link"></use></svg></button>`:""}<button data-a="editar" data-id="${p.id}" title="Editar"><svg><use href="#i-edit"></use></svg></button><button data-a="desactivar" data-id="${p.id}" title="Desactivar"><svg><use href="#i-trash"></use></svg></button></div></div></div></article>`}
function accion(a,id){const p=estado.productos.find(x=>x.id===id);if(!p)return;if(a==="editar")abrirModal(p);if(a==="abrir")window.open(p.archivoId,"_blank","noopener");if(a==="desactivar")desactivar(p)}
function abrirModal(p=null){estado.editando=p?.id||"";E.form.reset();C.precioCompra.value=0;C.duracionDias.value=0;C.stockMinimo.value=0;C.controlarStock.value="NO";C.estado.value="ACTIVO";E.titulo.textContent=p?"Editar producto":"Nuevo producto";if(p)ids.forEach(id=>{if(p[id]!=null)C[id].value=p[id]});E.modal.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarModal(){E.modal.classList.remove("visible");document.body.style.overflow="";estado.editando=""}
async function guardar(ev){ev.preventDefault();const r={id:estado.editando};ids.forEach(id=>r[id]=C[id].value);if(!r.nombre||!r.categoriaId||r.precioVenta==="")return msg("Nombre, categoría y precio de venta son obligatorios.","error");E.guardar.disabled=true;E.guardar.textContent="Guardando...";try{await post({action:"guardarProducto",registro:r});cerrarModal();msg("Producto guardado correctamente.");await cargar()}catch(e){msg(e.message,"error")}finally{E.guardar.disabled=false;E.guardar.textContent="Guardar producto"}}
async function desactivar(p){if(!confirm(`¿Desactivar ${p.nombre}?`))return;try{await post({action:"desactivarProducto",id:p.id});msg("Producto desactivado.");await cargar()}catch(e){msg(e.message,"error")}}
function kpis(){E.kTotal.textContent=estado.productos.length;E.kActivos.textContent=estado.productos.filter(p=>p.estado==="ACTIVO").length;E.kStock.textContent=estado.productos.filter(p=>p.controlarStock==="SI").length;E.kValor.textContent=money(estado.productos.reduce((s,p)=>s+Number(p.precioVenta||0),0))}
const money=n=>Number(n||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const escAttr=v=>esc(v).replace(/'/g,"&#39;");
E.nuevo.onclick=()=>abrirModal();E.cerrarModal.onclick=E.cancelar.onclick=cerrarModal;E.modal.onclick=e=>{if(e.target===E.modal)cerrarModal()};E.form.onsubmit=guardar;E.buscar.oninput=()=>{estado.texto=E.buscar.value.trim();render()};E.filtroCat.onchange=()=>{estado.categoria=E.filtroCat.value;render()};E.filtroEstado.onchange=()=>{estado.filtroEstado=E.filtroEstado.value;render()};E.actualizar.onclick=cargar;E.abrir.onclick=()=>{E.menu.classList.add("abierto");E.capa.classList.add("visible")};E.cerrar.onclick=()=>{E.menu.classList.remove("abierto");E.capa.classList.remove("visible")};E.capa.onclick=()=>E.cerrar.click();E.salir.onclick=()=>{if(confirm("¿Cerrar sesión?"))location.href="index.html"};$$("[data-pagina]").forEach(a=>a.onclick=e=>{e.preventDefault();msg(`La sección ${a.dataset.pagina} se creará después.`,"informacion")});cargar();
})();