(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{},state={respuestas:[],texto:"",respuesta:"TODAS",estado:"TODOS"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const E={menu:$("#menuLateral"),capa:$("#capaOscura"),abrir:$("#botonAbrirMenu"),cerrar:$("#botonCerrarMenu"),salir:$("#botonCerrarSesion"),actualizar:$("#botonActualizar"),conexion:$("#estadoConexion"),mensaje:$("#mensajePanel"),tabla:$("#tablaRespuestasBody"),cargando:$("#cargandoRespuestas"),vacio:$("#estadoVacio"),buscar:$("#buscarRespuesta"),filtroRespuesta:$("#filtroRespuesta"),filtroEstado:$("#filtroEstado"),kPend:$("#kpiPendientes"),kRen:$("#kpiRenovar"),kNo:$("#kpiNoRenovar"),kPor:$("#kpiPorVencer"),contador:$("#contadorPendientes")};
function msg(t,tipo="exito"){E.mensaje.textContent=t;E.mensaje.className=`mensaje-flotante visible ${tipo}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje-flotante",4000)}
async function get(action){const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action",action);u.searchParams.set("claveApi",cfg.API_KEY_SOCIOS);const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function post(body){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...body,claveApi:cfg.API_KEY_SOCIOS})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function cargar(){E.cargando.hidden=false;E.vacio.hidden=true;E.tabla.innerHTML="";try{const d=await get("listarRespuestasRenovacion");state.respuestas=d.registros||[];render();E.conexion.textContent="Google Sheets conectado";E.conexion.className="estado-conexion conectado"}catch(e){E.cargando.hidden=true;E.vacio.hidden=false;E.conexion.textContent="Sin conexión";msg(e.message,"error")}}
function filtradas(){const t=state.texto.toLowerCase();return state.respuestas.filter(r=>(state.respuesta==="TODAS"||r.respuesta===state.respuesta)&&(state.estado==="TODOS"||r.estado===state.estado)&&(!t||[r.clienteNombre,r.productoNombre,r.respuesta,r.tipoServicio].join(" ").toLowerCase().includes(t)))}
function render(){const l=filtradas();E.cargando.hidden=true;E.vacio.hidden=!!l.length;E.tabla.innerHTML=l.map(row).join("");kpis();$$("[data-a-ren]").forEach(b=>b.onclick=()=>accion(b.dataset.aRen,b.dataset.id))}
function row(r){return `<tr><td><div class="celda-renovacion"><strong>${esc(r.clienteNombre)}</strong><small>+${esc(r.clienteTelefono)}</small></div></td><td><div class="celda-renovacion"><strong>${esc(r.productoNombre)}</strong><small>${esc(r.tipoServicio)}</small></div></td><td><span class="respuesta-badge ${r.respuesta.toLowerCase()}">${esc(r.respuesta)}</span></td><td>${fechaHora(r.fechaRespuesta)}</td><td>${fecha(r.fechaVencimiento)}</td><td>${Number(r.diasRestantes||0)}</td><td><span class="estado-badge ${r.estado.toLowerCase()}">${esc(r.estado)}</span></td><td><div class="acciones-renovacion"><button class="whatsapp" data-a-ren="whatsapp" data-id="${r.id}" title="Contactar cliente"><svg><use href="#i-whatsapp"></use></svg></button>${r.estado==="PENDIENTE"?`<button class="procesar" data-a-ren="procesar" data-id="${r.id}" title="Marcar procesado"><svg><use href="#i-check"></use></svg></button>`:""}</div></td></tr>`}
function accion(a,id){const r=state.respuestas.find(x=>x.id===id);if(!r)return;if(a==="whatsapp"){const n=String(r.clienteTelefono||"").replace(/\D/g,"");const texto=r.respuesta==="RENOVAR"?`Hola ${r.clienteNombre}, recibimos tu solicitud para renovar ${r.productoNombre}. Te enviaremos las instrucciones de pago.`:`Hola ${r.clienteNombre}, recibimos tu respuesta de no renovar ${r.productoNombre}. El servicio finalizará en la fecha indicada.`;window.open(`https://wa.me/${n}?text=${encodeURIComponent(texto)}`,"_blank","noopener")}if(a==="procesar")procesar(r)}
async function procesar(r){if(!confirm("¿Marcar esta respuesta como procesada?"))return;try{await post({action:"procesarRespuestaRenovacion",respuestaId:r.id});msg("Respuesta marcada como procesada.");await cargar()}catch(e){msg(e.message,"error")}}
function kpis(){const p=state.respuestas.filter(r=>r.estado==="PENDIENTE").length,ren=state.respuestas.filter(r=>r.respuesta==="RENOVAR").length,no=state.respuestas.filter(r=>r.respuesta==="NO_RENOVAR").length,por=state.respuestas.filter(r=>Number(r.diasRestantes)>=0&&Number(r.diasRestantes)<=3).length;E.kPend.textContent=p;E.kRen.textContent=ren;E.kNo.textContent=no;E.kPor.textContent=por;E.contador.textContent=p}
const fecha=v=>v?new Date(v+"T00:00:00").toLocaleDateString("es-ES"):"",fechaHora=v=>v?new Date(v).toLocaleString("es-ES"):"",esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
E.actualizar.onclick=cargar;E.buscar.oninput=()=>{state.texto=E.buscar.value.trim();render()};E.filtroRespuesta.onchange=()=>{state.respuesta=E.filtroRespuesta.value;render()};E.filtroEstado.onchange=()=>{state.estado=E.filtroEstado.value;render()};E.abrir.onclick=()=>{E.menu.classList.add("abierto");E.capa.classList.add("visible")};E.cerrar.onclick=()=>{E.menu.classList.remove("abierto");E.capa.classList.remove("visible")};E.capa.onclick=()=>E.cerrar.click();E.salir.onclick=()=>{if(confirm("¿Cerrar sesión?"))location.href="index.html"};cargar();
})();