(()=>{"use strict";const A=window.MD20AdminAPI,$=s=>document.querySelector(s);let ventas=[],clientes=[],pagos=[];const num=n=>Number(n||0),fmt=(n,m='USD')=>`${num(n).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})} ${m}`;
function nav(){const m=$("#menuLateral"),c=$("#capaOscura");$("#botonAbrirMenu")?.addEventListener("click",()=>{m?.classList.add("abierto");c?.classList.add("visible")});$("#botonCerrarMenu")?.addEventListener("click",()=>{m?.classList.remove("abierto");c?.classList.remove("visible")});c?.addEventListener("click",()=>$("#botonCerrarMenu")?.click())}
function render(){const pagadas=ventas.filter(v=>String(v.estadoPago||'').toUpperCase()==='PAGADO');const pendientes=ventas.filter(v=>['PENDIENTE','PARCIAL'].includes(String(v.estadoPago||'').toUpperCase()));$("#rVentas").textContent=ventas.length;$("#rIngresos").textContent=fmt(pagadas.reduce((s,v)=>s+num(v.montoPagado||v.total),0),'USD');$("#rPendiente").textContent=fmt(pendientes.reduce((s,v)=>s+num(v.saldoPendiente||v.total),0),'USD');$("#rClientes").textContent=clientes.length;
const prod={};ventas.forEach(v=>{const k=v.productoNombre||'Sin producto';prod[k]=(prod[k]||0)+1});const top=Object.entries(prod).sort((a,b)=>b[1]-a[1]).slice(0,8),max=top[0]?.[1]||1;$("#topProductos").innerHTML=top.length?top.map(([k,n])=>`<div class="report-row"><div><strong>${A.esc(k)}</strong><small>${n} operación(es)</small><div class="bar-track"><div class="bar-fill" style="width:${Math.round(n/max*100)}%"></div></div></div><b>${n}</b></div>`).join(''):'<div class="admin-empty">Sin ventas registradas.</div>';
const mets={};pagos.filter(p=>String(p.estado||'').toUpperCase()==='CONFIRMADO').forEach(p=>{const k=p.metodoPagoNombre||p.metodoNombre||p.metodo||p.metodoPagoId||'Sin método';mets[k]=(mets[k]||0)+num(p.monto)});const mm=Object.entries(mets).sort((a,b)=>b[1]-a[1]);$("#metodosPago").innerHTML=mm.length?mm.map(([k,n])=>`<div class="report-row"><div><strong>${A.esc(k)}</strong><small>Pagos confirmados</small></div><b>${fmt(n,pagos.find(p=>(p.metodoPagoNombre||p.metodoNombre||p.metodo||p.metodoPagoId||'Sin método')===k)?.moneda||'USD')}</b></div>`).join(''):'<div class="admin-empty">Sin pagos confirmados.</div>';
const rec=[...ventas].sort((a,b)=>String(b.fechaVenta||'').localeCompare(String(a.fechaVenta||''))).slice(0,15);$("#tablaReportes").innerHTML=rec.length?rec.map(v=>`<tr><td><strong>${A.esc(v.numeroVenta||v.id)}</strong><small>${A.esc(v.id||'')}</small></td><td>${A.esc(v.clienteNombre||'—')}</td><td>${A.esc(v.productoNombre||'—')}</td><td>${A.esc(v.fechaVenta||'—')}</td><td><strong>${fmt(v.total,v.moneda||'USD')}</strong></td><td><span class="admin-chip ${String(v.estadoPago).toUpperCase()==='PAGADO'?'green':'orange'}">${A.esc(v.estadoPago||'PENDIENTE')}</span></td><td><span class="admin-chip ${String(v.estadoEntrega).toUpperCase().includes('ENTREG')?'green':'blue'}">${A.esc(v.estadoEntrega||'PENDIENTE')}</span></td></tr>`).join(''):'<tr><td colspan="7" class="admin-empty">Sin ventas registradas.</td></tr>'}
async function cargar(){try{const [v,c,p]=await Promise.all([A.get('listarVentas'),A.get('listarClientes'),A.get('listarPagosMD20')]);ventas=v.registros||[];clientes=c.registros||[];pagos=p.registros||[];render();A.toast('Reportes actualizados.')}catch(e){A.toast(e.message,'error')}}
function csv(){const rows=[['Venta','Cliente','Producto','Fecha','Total','Moneda','Pago','Entrega'],...ventas.map(v=>[v.numeroVenta||v.id,v.clienteNombre,v.productoNombre,v.fechaVenta,v.total,v.moneda,v.estadoPago,v.estadoEntrega])];const text='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='mundo-digital-2-0-reporte-ventas.csv';a.click();URL.revokeObjectURL(a.href)}
nav();$("#botonActualizar")?.addEventListener('click',cargar);$("#btnCsv")?.addEventListener('click',csv);$("#btnImprimir")?.addEventListener('click',()=>window.print());cargar();})();
