(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{}, state={suscripciones:[],clientes:[],productos:[],ventas:[],proveedores:[],cuentas:[],texto:"",estado:"TODOS",editando:""};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={menu:$("#menuLateral"),capa:$("#capaOscura"),abrir:$("#botonAbrirMenu"),cerrar:$("#botonCerrarMenu"),salir:$("#botonCerrarSesion"),nueva:$("#botonNuevaSuscripcion"),modal:$("#modalSuscripcion"),cerrarModal:$("#botonCerrarModal"),cancelar:$("#botonCancelar"),form:$("#formularioSuscripcion"),titulo:$("#tituloModal"),guardar:$("#botonGuardar"),tabla:$("#tablaSuscripcionesBody"),cargando:$("#cargandoSuscripciones"),vacio:$("#estadoVacio"),buscar:$("#buscarSuscripcion"),filtro:$("#filtroEstado"),actualizar:$("#botonActualizar"),conexion:$("#estadoConexion"),mensaje:$("#mensajePanel"),kTotal:$("#kpiTotal"),kActivas:$("#kpiActivas"),kPor:$("#kpiPorVencer"),kVenc:$("#kpiVencidas"),contador:$("#contadorAlertas"),modalDetalle:$("#modalDetalle"),cerrarDetalle:$("#botonCerrarDetalle"),tituloDetalle:$("#tituloDetalle"),contenidoDetalle:$("#contenidoDetalle")};
const ids=["clienteId","productoId","ventaId","proveedorId","cuentaId","plataforma","tipoCuenta","usuarioCuenta","contrasenaCuenta","perfil","pin","fechaInicio","tiempoMeses","fechaVencimiento","precioRenovacion","moneda","estadoRenovacion","estado","renovacionAutomatica","notas"];
const C=ids.reduce((o,id)=>(o[id]=$("#"+id),o),{});
function msg(t,tipo="exito"){E.mensaje.textContent=t;E.mensaje.className=`mensaje-flotante visible ${tipo}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje-flotante",4000)}
async function get(action,extra={}){const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action",action);u.searchParams.set("claveApi",cfg.API_KEY_SOCIOS);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function post(body){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...body,claveApi:cfg.API_KEY_SOCIOS})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function cargar(){E.cargando.hidden=false;E.vacio.hidden=true;E.tabla.innerHTML="";try{const [s,c,p,v,pr,cu]=await Promise.all([get("listarSuscripciones"),get("listarClientes"),get("listarProductos"),get("listarVentas"),get("listarSocios",{tipo:"PROVEEDOR"}),get("listarCuentasDisponibles")]);state.suscripciones=s.registros||[];state.clientes=(c.registros||[]).filter(x=>x.estado==="ACTIVO");state.productos=(p.registros||[]).filter(x=>x.estado==="ACTIVO");state.ventas=(v.registros||[]).filter(x=>x.estadoPago==="PAGADO");state.proveedores=pr.registros||[];state.cuentas=cu.registros||[];llenar();render();E.conexion.textContent="Google Sheets conectado";E.conexion.className="estado-conexion conectado"}catch(e){E.cargando.hidden=true;E.vacio.hidden=false;E.conexion.textContent="Sin conexión";msg(e.message,"error")}}
function llenar(){
C.clienteId.innerHTML='<option value="">Selecciona un cliente</option>'+state.clientes.map(x=>`<option value="${esc(x.id)}">${esc(x.nombreCompleto)}</option>`).join("");
C.productoId.innerHTML='<option value="">Selecciona un producto</option>'+state.productos.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)}</option>`).join("");
C.ventaId.innerHTML='<option value="">Sin venta relacionada</option>'+state.ventas.map(x=>`<option value="${esc(x.id)}">${esc(x.numeroVenta)} · ${esc(x.clienteNombre)} · ${esc(x.productoNombre)}</option>`).join("");
C.proveedorId.innerHTML='<option value="">Sin proveedor</option>'+state.proveedores.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} ${esc(x.apellido||"")} · ${esc(x.producto||"")}</option>`).join("");
C.cuentaId.innerHTML='<option value="">Selecciona una cuenta disponible</option>'+state.cuentas.map(x=>`<option value="${esc(x.id)}">${esc(x.plataforma)} · ${esc(x.usuarioCuenta||"Sin usuario")} · ${esc(x.perfil||x.tipoCuenta||"")}</option>`).join("");
}
function filtradas(){const t=state.texto.toLowerCase();return state.suscripciones.filter(s=>(state.estado==="TODOS"||s.estado===state.estado)&&(!t||[s.clienteNombre,s.productoNombre,s.usuarioCuenta,s.proveedorNombre,s.plataforma].join(" ").toLowerCase().includes(t)))}
function render(){const l=filtradas();E.cargando.hidden=true;E.vacio.hidden=!!l.length;E.tabla.innerHTML=l.map(row).join("");kpis();$$("[data-a]").forEach(b=>b.onclick=()=>accion(b.dataset.a,b.dataset.id))}
function row(s){return `<tr><td><div class="celda-sus"><strong>${esc(s.clienteNombre)}</strong><small>+${esc(s.clienteTelefono)}</small></div></td><td><div class="celda-sus"><strong>${esc(s.productoNombre)}</strong><small>${esc(s.plataforma||"Sin plataforma")}</small></div></td><td><div class="celda-sus"><strong>${esc(s.usuarioCuenta||"Sin usuario")}</strong><small>${esc(s.perfil||"Sin perfil")}</small></div></td><td><div class="celda-sus"><strong>${esc(s.proveedorNombre||"Sin proveedor")}</strong><small>${esc(s.proveedorWhatsapp||"")}</small></div></td><td>${fecha(s.fechaInicio)}</td><td>${fecha(s.fechaVencimiento)}</td><td><strong>${Number(s.diasRestantes||0)}</strong></td><td><span class="renovacion-sus ${s.estadoRenovacion.toLowerCase()}">${esc(s.estadoRenovacion)}</span></td><td><span class="estado-sus ${s.estado.toLowerCase()}">${esc(s.estado)}</span></td><td><div class="acciones-sus"><button data-a="ver" data-id="${s.id}"><svg><use href="#i-eye"></use></svg></button><button data-a="editar" data-id="${s.id}"><svg><use href="#i-edit"></use></svg></button></div></td></tr>`}
function accion(a,id){const s=state.suscripciones.find(x=>x.id===id);if(!s)return;if(a==="ver")ver(s);if(a==="editar")abrirModal(s)}
function aplicarCuentaSeleccionada(){
  const cuenta=state.cuentas.find(x=>x.id===C.cuentaId.value);
  if(!cuenta)return;
  C.proveedorId.value=cuenta.proveedorId||"";
  C.productoId.value=cuenta.productoId||C.productoId.value;
  C.plataforma.value=cuenta.plataforma||"";
  C.tipoCuenta.value=cuenta.tipoCuenta||"ACCESO";
  C.usuarioCuenta.value=cuenta.usuarioCuenta||"";
  C.contrasenaCuenta.value=cuenta.contrasenaCuenta||"";
  C.perfil.value=cuenta.perfil||"";
  C.pin.value=cuenta.pin||"";
  if(cuenta.moneda)C.moneda.value=cuenta.moneda;
}
function abrirModal(s=null){
state.editando=s?.id||"";
E.form.reset();
C.fechaInicio.value=hoy();C.tiempoMeses.value="1";C.precioRenovacion.value=0;C.moneda.value="USD";C.estadoRenovacion.value="SIN_RESPUESTA";C.estado.value="ACTIVA";C.renovacionAutomatica.value="NO";
E.titulo.textContent=s?"Editar suscripción":"Nueva suscripción";
if(s&&s.cuentaId&&!state.cuentas.some(x=>x.id===s.cuentaId)){
  C.cuentaId.insertAdjacentHTML("beforeend",`<option value="${esc(s.cuentaId)}">${esc(s.plataforma||"Cuenta asignada")} · ${esc(s.usuarioCuenta||s.cuentaId)}</option>`);
}
if(s)ids.forEach(id=>{if(s[id]!=null)C[id].value=s[id]});
calcularVencimiento();
E.modal.classList.add("visible");document.body.style.overflow="hidden";
}
function cerrarModal(){E.modal.classList.remove("visible");document.body.style.overflow="";state.editando=""}
function calcularVencimiento(){if(!C.fechaInicio.value)return C.fechaVencimiento.value="";const d=new Date(C.fechaInicio.value+"T00:00:00"),dia=d.getDate(),m=Number(C.tiempoMeses.value||1);d.setDate(1);d.setMonth(d.getMonth()+m);const ultimo=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(dia,ultimo));C.fechaVencimiento.value=d.toISOString().slice(0,10)}
async function guardar(ev){ev.preventDefault();if(!C.clienteId.value||!C.productoId.value||!C.fechaInicio.value)return msg("Cliente, producto y fecha de inicio son obligatorios.","error");const r={id:state.editando};ids.forEach(id=>r[id]=C[id].value);E.guardar.disabled=true;E.guardar.textContent="Guardando...";try{await post({action:"guardarSuscripcion",registro:r});cerrarModal();msg("Suscripción guardada correctamente.");await cargar()}catch(e){msg(e.message,"error")}finally{E.guardar.disabled=false;E.guardar.textContent="Guardar suscripción"}}
function ver(s){E.tituloDetalle.textContent=`${s.clienteNombre} · ${s.productoNombre}`;E.contenidoDetalle.innerHTML=`<div class="detalle-grid-sus"><div class="detalle-item-sus"><span>Cliente</span><strong>${esc(s.clienteNombre)}</strong></div><div class="detalle-item-sus"><span>WhatsApp</span><strong>+${esc(s.clienteTelefono)}</strong></div><div class="detalle-item-sus"><span>Producto</span><strong>${esc(s.productoNombre)}</strong></div><div class="detalle-item-sus"><span>Proveedor</span><strong>${esc(s.proveedorNombre||"Sin proveedor")}</strong></div><div class="detalle-item-sus"><span>Plataforma</span><strong>${esc(s.plataforma||"")}</strong></div><div class="detalle-item-sus"><span>Tipo de cuenta</span><strong>${esc(s.tipoCuenta)}</strong></div><div class="detalle-item-sus"><span>Usuario</span><strong>${esc(s.usuarioCuenta||"")}</strong></div><div class="detalle-item-sus"><span>Contraseña</span><strong>${esc(s.contrasenaCuenta||"")}</strong></div><div class="detalle-item-sus"><span>Perfil</span><strong>${esc(s.perfil||"")}</strong></div><div class="detalle-item-sus"><span>PIN</span><strong>${esc(s.pin||"")}</strong></div><div class="detalle-item-sus"><span>Inicio</span><strong>${fecha(s.fechaInicio)}</strong></div><div class="detalle-item-sus"><span>Vencimiento</span><strong>${fecha(s.fechaVencimiento)}</strong></div><div class="detalle-item-sus"><span>Días restantes</span><strong>${Number(s.diasRestantes||0)}</strong></div><div class="detalle-item-sus"><span>Precio renovación</span><strong>${money(s.precioRenovacion)} ${esc(s.moneda)}</strong></div><div class="detalle-item-sus"><span>Estado renovación</span><strong>${esc(s.estadoRenovacion)}</strong></div><div class="detalle-item-sus"><span>Estado servicio</span><strong>${esc(s.estado)}</strong></div><div class="detalle-item-sus ancho"><span>Notas</span><strong>${esc(s.notas||"Sin notas")}</strong></div></div>`;E.modalDetalle.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarDetalle(){E.modalDetalle.classList.remove("visible");document.body.style.overflow=""}
function kpis(){const a=state.suscripciones.filter(x=>x.estado==="ACTIVA").length,p=state.suscripciones.filter(x=>x.estado==="POR_VENCER").length,v=state.suscripciones.filter(x=>x.estado==="VENCIDA").length;E.kTotal.textContent=state.suscripciones.length;E.kActivas.textContent=a;E.kPor.textContent=p;E.kVenc.textContent=v;E.contador.textContent=p+v}
const hoy=()=>new Date().toISOString().slice(0,10),money=n=>Number(n||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}),fecha=v=>v?new Date(v+"T00:00:00").toLocaleDateString("es-ES"):"",esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
E.nueva.onclick=()=>abrirModal();E.cerrarModal.onclick=E.cancelar.onclick=cerrarModal;E.modal.onclick=e=>{if(e.target===E.modal)cerrarModal()};E.cerrarDetalle.onclick=cerrarDetalle;E.modalDetalle.onclick=e=>{if(e.target===E.modalDetalle)cerrarDetalle()};E.form.onsubmit=guardar;C.cuentaId.onchange=aplicarCuentaSeleccionada;C.fechaInicio.onchange=calcularVencimiento;C.tiempoMeses.onchange=calcularVencimiento;E.buscar.oninput=()=>{state.texto=E.buscar.value.trim();render()};E.filtro.onchange=()=>{state.estado=E.filtro.value;render()};E.actualizar.onclick=cargar;E.abrir.onclick=()=>{E.menu.classList.add("abierto");E.capa.classList.add("visible")};E.cerrar.onclick=()=>{E.menu.classList.remove("abierto");E.capa.classList.remove("visible")};E.capa.onclick=()=>E.cerrar.click();E.salir.onclick=()=>{if(confirm("¿Cerrar sesión?"))location.href="index.html"};$$("[data-pagina]").forEach(a=>a.onclick=e=>{e.preventDefault();msg(`La sección ${a.dataset.pagina} se creará después.`,"informacion")});cargar();
})();