(()=>{"use strict";const A=window.MD20AdminAPI,$=s=>document.querySelector(s);let estado={usuarios:[],roles:[],vendedores:[]};
function nav(){const menu=$("#menuLateral"),capa=$("#capaOscura");$("#botonAbrirMenu")?.addEventListener("click",()=>{menu?.classList.add("abierto");capa?.classList.add("visible")});$("#botonCerrarMenu")?.addEventListener("click",()=>{menu?.classList.remove("abierto");capa?.classList.remove("visible")});capa?.addEventListener("click",()=>$("#botonCerrarMenu")?.click())}
const rolNombre=id=>(estado.roles.find(r=>r.id===id)||{}).nombre||id;const vendNombre=id=>{const v=estado.vendedores.find(x=>x.id===id);return v?(v.nombre||v.usuario||v.id):id||"—"};
function kpis(){const u=estado.usuarios;$("#kTotal").textContent=u.length;$("#kActivos").textContent=u.filter(x=>x.estado==="ACTIVO").length;$("#kAdmins").textContent=u.filter(x=>x.rolId==="ROL-ADMIN").length;$("#kVendedores").textContent=u.filter(x=>x.rolId==="ROL-VENDEDOR").length}
function llenarSelects(){const filtro=$("#filtroRol"),rol=$("#uRol"),vend=$("#uVendedor");const optRoles=estado.roles.map(r=>`<option value="${A.esc(r.id)}">${A.esc(r.nombre||r.id)}</option>`).join("");filtro.innerHTML='<option value="">Todos los roles</option>'+optRoles;rol.innerHTML=optRoles;vend.innerHTML='<option value="">Selecciona un vendedor...</option>'+estado.vendedores.filter(v=>v.estado!=="INACTIVO").map(v=>`<option value="${A.esc(v.id)}">${A.esc(v.nombre||v.usuario||v.id)} · ${A.esc(v.id)}</option>`).join("")}
function render(){kpis();const q=$("#buscarUsuario").value.trim().toLowerCase(),fr=$("#filtroRol").value;const arr=estado.usuarios.filter(u=>(!fr||u.rolId===fr)&&(!q||[u.nombreCompleto,u.usuario,u.correo,u.vendedorId].join(" ").toLowerCase().includes(q)));const body=$("#tablaUsuarios");if(!arr.length){body.innerHTML='<tr><td colspan="7" class="admin-empty">No hay usuarios que coincidan con el filtro.</td></tr>';return}body.innerHTML=arr.map(u=>`<tr><td><strong>${A.esc(u.nombreCompleto)}</strong><small>@${A.esc(u.usuario)} · ${A.esc(u.id)}</small></td><td><span class="admin-chip ${u.rolId==='ROL-ADMIN'?'orange':u.rolId==='ROL-VENDEDOR'?'blue':'green'}">${A.esc(rolNombre(u.rolId))}</span></td><td><strong>${A.esc(vendNombre(u.vendedorId))}</strong><small>${A.esc(u.vendedorId||'Sin asociación')}</small></td><td><strong>${A.esc(u.correo||'Sin correo')}</strong><small>${A.esc(u.telefono||'Sin teléfono')}</small></td><td>${A.esc(u.ultimoAcceso||'Sin registro')}</td><td><span class="admin-chip ${u.estado==='ACTIVO'?'green':'red'}">${A.esc(u.estado)}</span></td><td><div class="admin-row-actions"><button class="admin-btn small" data-edit="${A.esc(u.id)}">Editar</button><button class="admin-btn small ${u.estado==='ACTIVO'?'danger':'success'}" data-state="${A.esc(u.id)}" data-next="${u.estado==='ACTIVO'?'INACTIVO':'ACTIVO'}">${u.estado==='ACTIVO'?'Desactivar':'Activar'}</button></div></td></tr>`).join("")}
async function cargar(){try{const d=await A.get("listarUsuariosAdminMD20");estado={usuarios:d.registros||[],roles:d.roles||[],vendedores:d.vendedores||[]};llenarSelects();render();A.toast("Usuarios sincronizados con Google Sheets.")}catch(e){A.toast(e.message,"error")}}
function modal(open=true){$("#modalUsuario").classList.toggle("open",open)}
function ajustarVendedor(){const es=$("#uRol").value==="ROL-VENDEDOR";$("#campoVendedor").style.display=es?"flex":"none";$("#uVendedor").required=es}
function nuevo(){$("#formUsuario").reset();$("#usuarioId").value="";$("#tituloModalUsuario").textContent="Nuevo usuario";$("#labelClave").textContent="Contraseña *";if(estado.roles.some(r=>r.id==="ROL-VENDEDOR"))$("#uRol").value="ROL-VENDEDOR";$("#uEstado").value="ACTIVO";ajustarVendedor();modal(true)}
function editar(id){const u=estado.usuarios.find(x=>x.id===id);if(!u)return;$("#usuarioId").value=u.id;$("#uNombre").value=u.nombreCompleto;$("#uUsuario").value=u.usuario;$("#uCorreo").value=u.correo;$("#uTelefono").value=u.telefono;$("#uRol").value=u.rolId;$("#uVendedor").value=u.vendedorId||"";$("#uEstado").value=u.estado;$("#uClave").value="";$("#tituloModalUsuario").textContent="Editar usuario";$("#labelClave").textContent="Nueva contraseña (opcional)";ajustarVendedor();modal(true)}
async function guardar(e){e.preventDefault();const registro={id:$("#usuarioId").value,nombreCompleto:$("#uNombre").value,usuario:$("#uUsuario").value,correo:$("#uCorreo").value,telefono:$("#uTelefono").value,rolId:$("#uRol").value,vendedorId:$("#uVendedor").value,estado:$("#uEstado").value,contrasena:$("#uClave").value};try{await A.post("guardarUsuarioAdminMD20",{registro});modal(false);A.toast("Usuario guardado correctamente.");await cargar()}catch(e2){A.toast(e2.message,"error")}}
async function cambiar(id,next){const u=estado.usuarios.find(x=>x.id===id);if(!u)return;if(!confirm(`¿Cambiar a ${next} el acceso de ${u.nombreCompleto}?`))return;try{await A.post("cambiarEstadoUsuarioAdminMD20",{usuarioId:id,estado:next});A.toast(`Usuario ${next.toLowerCase()}.`);await cargar()}catch(e){A.toast(e.message,"error")}}
nav();$("#botonActualizar")?.addEventListener("click",cargar);$("#btnNuevoUsuario")?.addEventListener("click",nuevo);$("#cerrarModalUsuario")?.addEventListener("click",()=>modal(false));$("#cancelarUsuario")?.addEventListener("click",()=>modal(false));$("#modalUsuario")?.addEventListener("click",e=>{if(e.target.id==="modalUsuario")modal(false)});$("#uRol")?.addEventListener("change",ajustarVendedor);$("#formUsuario")?.addEventListener("submit",guardar);$("#buscarUsuario")?.addEventListener("input",render);$("#filtroRol")?.addEventListener("change",render);document.addEventListener("click",e=>{const ed=e.target.closest("[data-edit]");if(ed)editar(ed.dataset.edit);const st=e.target.closest("[data-state]");if(st)cambiar(st.dataset.state,st.dataset.next)});cargar();})();
