(() => {
"use strict";
const cfg=window.MUNDO_DIGITAL_CONFIG||{}, state={ventas:[],clientes:[],productos:[],metodos:[],texto:"",pago:"TODOS"};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={menu:$("#menuLateral"),capa:$("#capaOscura"),abrir:$("#botonAbrirMenu"),cerrar:$("#botonCerrarMenu"),salir:$("#botonCerrarSesion"),nueva:$("#botonNuevaVenta"),modal:$("#modalVenta"),cerrarModal:$("#botonCerrarModal"),cancelar:$("#botonCancelar"),form:$("#formularioVenta"),guardar:$("#botonGuardar"),tabla:$("#tablaVentasBody"),cargando:$("#cargandoVentas"),vacio:$("#estadoVacio"),buscar:$("#buscarVenta"),filtro:$("#filtroPago"),actualizar:$("#botonActualizar"),conexion:$("#estadoConexion"),mensaje:$("#mensajePanel"),kTotal:$("#kpiTotal"),kPend:$("#kpiPendientes"),kPag:$("#kpiPagadas"),kIng:$("#kpiIngresos"),contador:$("#contadorPendientes"),modalDetalle:$("#modalDetalle"),cerrarDetalle:$("#botonCerrarDetalle"),tituloDetalle:$("#tituloDetalle"),contenidoDetalle:$("#contenidoDetalle"),subtotal:$("#vistaSubtotal"),vistaDesc:$("#vistaDescuento"),total:$("#vistaTotal")};
const C=["clienteId","productoId","cantidad","precioUnitario","descuento","duracionDias","metodoPagoId","referencia","comprobanteUrl","moneda","canalVenta","notas"].reduce((o,id)=>(o[id]=$("#"+id),o),{});
function msg(t,tipo="exito"){E.mensaje.textContent=t;E.mensaje.className=`mensaje-flotante visible ${tipo}`;clearTimeout(msg.t);msg.t=setTimeout(()=>E.mensaje.className="mensaje-flotante",4000)}
async function get(action,extra={}){if(!cfg.APPS_SCRIPT_URL||!cfg.API_KEY_SOCIOS)throw Error("Falta configurar la conexión.");const u=new URL(cfg.APPS_SCRIPT_URL);u.searchParams.set("action",action);u.searchParams.set("claveApi",cfg.API_KEY_SOCIOS);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{redirect:"follow"}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function post(body){const r=await fetch(cfg.APPS_SCRIPT_URL,{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...body,claveApi:cfg.API_KEY_SOCIOS})}),d=await r.json();if(!d.ok)throw Error(d.mensaje||"Error");return d}
async function cargar(){E.cargando.hidden=false;E.vacio.hidden=true;E.tabla.innerHTML="";try{const [v,c,p,m]=await Promise.all([get("listarVentas"),get("listarClientes"),get("listarProductos"),get("listarMetodosPago")]);state.ventas=v.registros||[];state.clientes=(c.registros||[]).filter(x=>x.estado==="ACTIVO");state.productos=(p.registros||[]).filter(x=>x.estado==="ACTIVO");state.metodos=m.registros||[];llenarSelects();render();E.conexion.textContent="Google Sheets conectado";E.conexion.className="estado-conexion conectado"}catch(e){E.cargando.hidden=true;E.vacio.hidden=false;E.conexion.textContent="Sin conexión";msg(e.message,"error")}}
function llenarSelects(){C.clienteId.innerHTML='<option value="">Selecciona un cliente</option>'+state.clientes.map(x=>`<option value="${esc(x.id)}">${esc(x.nombreCompleto)} · +${esc(x.telefono)}</option>`).join("");C.productoId.innerHTML='<option value="">Selecciona un producto</option>'+state.productos.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} · ${money(x.precioVenta)} ${esc(x.moneda)}</option>`).join("");C.metodoPagoId.innerHTML='<option value="">Sin especificar</option>'+state.metodos.map(x=>`<option value="${esc(x.id)}">${esc(x.nombre)} · ${esc(x.moneda)}</option>`).join("")}
function filtradas(){const t=state.texto.toLowerCase();return state.ventas.filter(v=>(state.pago==="TODOS"||v.estadoPago===state.pago)&&(!t||[v.numeroVenta,v.clienteNombre,v.productoNombre,v.referencia,v.metodoPagoNombre].join(" ").toLowerCase().includes(t)))}
function render(){const l=filtradas();E.cargando.hidden=true;E.vacio.hidden=!!l.length;E.tabla.innerHTML=l.map(row).join("");kpis();$$("[data-a]").forEach(b=>b.onclick=()=>accion(b.dataset.a,b.dataset.id))}
function row(v){return `<tr><td><div class="venta-numero"><strong>${esc(v.numeroVenta)}</strong><small>${esc(v.id)}</small></div></td><td><div class="venta-cliente"><strong>${esc(v.clienteNombre)}</strong><small>+${esc(v.clienteTelefono)}</small></div></td><td><div class="venta-producto"><strong>${esc(v.productoNombre)}</strong><small>${Number(v.cantidad)} unidad(es)</small></div></td><td>${fecha(v.fechaVenta)}</td><td><strong>${money(v.total)} ${esc(v.moneda)}</strong><br><small>Pagado: ${money(v.montoPagado)}</small></td><td>${esc(v.metodoPagoNombre||"Sin especificar")}<br><small>${esc(v.referencia||"Sin referencia")}</small></td><td><span class="estado-venta ${v.estadoPago.toLowerCase()}">${esc(v.estadoPago)}</span></td><td><span class="estado-venta ${v.estadoEntrega.toLowerCase()}">${esc(v.estadoEntrega)}</span></td><td><div class="acciones-venta"><button data-a="ver" data-id="${v.id}" title="Ver detalle"><svg><use href="#i-eye"></use></svg></button>${v.estadoPago==="PENDIENTE"?`<button class="pagar" data-a="pagar" data-id="${v.id}" title="Marcar pagado"><svg><use href="#i-check"></use></svg></button><button class="rechazar" data-a="rechazar" data-id="${v.id}" title="Rechazar"><svg><use href="#i-x"></use></svg></button>`:""}</div></td></tr>`}
function accion(a,id){const v=state.ventas.find(x=>x.id===id);if(!v)return;if(a==="ver")verDetalle(v);if(a==="pagar")cambiarPago(v,"PAGADO");if(a==="rechazar")cambiarPago(v,"RECHAZADO")}
function abrirModal(){E.form.reset();C.cantidad.value=1;C.descuento.value=0;C.precioUnitario.value="";C.duracionDias.value=0;C.moneda.value="USD";calcular();E.modal.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarModal(){E.modal.classList.remove("visible");document.body.style.overflow=""}
function productoElegido(){return state.productos.find(p=>p.id===C.productoId.value)}
function alElegirProducto(){const p=productoElegido();if(!p)return;C.precioUnitario.value=Number(p.precioVenta||0);C.duracionDias.value=Number(p.duracionDias||0);C.moneda.value=p.moneda||"USD";calcular()}
function totales(){const cant=Math.max(1,Number(C.cantidad.value||1)),precio=Math.max(0,Number(C.precioUnitario.value||0)),desc=Math.max(0,Number(C.descuento.value||0)),sub=cant*precio,total=Math.max(0,sub-desc);return{cant,precio,desc,sub,total}}
function calcular(){const t=totales();E.subtotal.textContent=money(t.sub);E.vistaDesc.textContent=money(t.desc);E.total.textContent=money(t.total)}
async function guardar(ev){ev.preventDefault();const t=totales();if(!C.clienteId.value||!C.productoId.value)return msg("Selecciona cliente y producto.","error");E.guardar.disabled=true;E.guardar.textContent="Registrando...";try{await post({action:"crearVenta",registro:{clienteId:C.clienteId.value,productoId:C.productoId.value,cantidad:t.cant,precioUnitario:t.precio,descuento:t.desc,duracionDias:Number(C.duracionDias.value||0),metodoPagoId:C.metodoPagoId.value,referencia:C.referencia.value.trim(),comprobanteUrl:C.comprobanteUrl.value.trim(),moneda:C.moneda.value,canalVenta:C.canalVenta.value,notas:C.notas.value.trim()}});cerrarModal();msg("Venta registrada como PENDIENTE.");await cargar()}catch(e){msg(e.message,"error")}finally{E.guardar.disabled=false;E.guardar.textContent="Registrar venta pendiente"}}
async function cambiarPago(v,estado){const texto=estado==="PAGADO"?`¿Confirmas que la venta ${v.numeroVenta} está pagada?`:`¿Rechazar el pago de ${v.numeroVenta}?`;if(!confirm(texto))return;try{await post({action:"cambiarEstadoPagoVenta",ventaId:v.id,estado});msg(estado==="PAGADO"?"Pago confirmado. La venta quedó pendiente de entrega.":"Pago rechazado.");await cargar()}catch(e){msg(e.message,"error")}}
function verDetalle(v){E.tituloDetalle.textContent=v.numeroVenta;E.contenidoDetalle.innerHTML=`<div class="detalle-grid"><div class="detalle-campo"><span>Cliente</span><strong>${esc(v.clienteNombre)}</strong></div><div class="detalle-campo"><span>WhatsApp</span><strong>+${esc(v.clienteTelefono)}</strong></div><div class="detalle-campo"><span>Producto</span><strong>${esc(v.productoNombre)}</strong></div><div class="detalle-campo"><span>Cantidad</span><strong>${Number(v.cantidad)}</strong></div><div class="detalle-campo"><span>Subtotal</span><strong>${money(v.subtotal)} ${esc(v.moneda)}</strong></div><div class="detalle-campo"><span>Descuento</span><strong>${money(v.descuento)} ${esc(v.moneda)}</strong></div><div class="detalle-campo"><span>Total</span><strong>${money(v.total)} ${esc(v.moneda)}</strong></div><div class="detalle-campo"><span>Pago</span><strong>${esc(v.estadoPago)}</strong></div><div class="detalle-campo"><span>Método</span><strong>${esc(v.metodoPagoNombre||"Sin especificar")}</strong></div><div class="detalle-campo"><span>Referencia</span><strong>${esc(v.referencia||"Sin referencia")}</strong></div><div class="detalle-campo ancho"><span>Notas</span><strong>${esc(v.notas||"Sin notas")}</strong></div></div><div class="detalle-acciones">${v.comprobanteUrl?`<a href="${escAttr(v.comprobanteUrl)}" target="_blank" rel="noopener">Ver comprobante</a>`:""}${v.estadoPago==="PAGADO"?'<button type="button" disabled>Entrega pendiente de autorización</button>':""}</div>`;E.modalDetalle.classList.add("visible");document.body.style.overflow="hidden"}
function cerrarDetalle(){E.modalDetalle.classList.remove("visible");document.body.style.overflow=""}
function kpis(){const pend=state.ventas.filter(v=>v.estadoPago==="PENDIENTE").length,pag=state.ventas.filter(v=>v.estadoPago==="PAGADO").length,ing=state.ventas.filter(v=>v.estadoPago==="PAGADO").reduce((s,v)=>s+Number(v.total||0),0);E.kTotal.textContent=state.ventas.length;E.kPend.textContent=pend;E.kPag.textContent=pag;E.kIng.textContent=money(ing);E.contador.textContent=pend}
const money=n=>Number(n||0).toLocaleString("es-ES",{minimumFractionDigits:2,maximumFractionDigits:2}), fecha=v=>v?new Date(v+"T00:00:00").toLocaleDateString("es-ES"):"", esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),escAttr=v=>esc(v).replace(/'/g,"&#39;");
E.nueva.onclick=abrirModal;E.cerrarModal.onclick=E.cancelar.onclick=cerrarModal;E.modal.onclick=e=>{if(e.target===E.modal)cerrarModal()};E.cerrarDetalle.onclick=cerrarDetalle;E.modalDetalle.onclick=e=>{if(e.target===E.modalDetalle)cerrarDetalle()};E.form.onsubmit=guardar;C.productoId.onchange=alElegirProducto;[C.cantidad,C.precioUnitario,C.descuento].forEach(x=>x.oninput=calcular);E.buscar.oninput=()=>{state.texto=E.buscar.value.trim();render()};E.filtro.onchange=()=>{state.pago=E.filtro.value;render()};E.actualizar.onclick=cargar;E.abrir.onclick=()=>{E.menu.classList.add("abierto");E.capa.classList.add("visible")};E.cerrar.onclick=()=>{E.menu.classList.remove("abierto");E.capa.classList.remove("visible")};E.capa.onclick=()=>E.cerrar.click();E.salir.onclick=()=>{if(confirm("¿Cerrar sesión?"))location.href="index.html"};$$("[data-pagina]").forEach(a=>a.onclick=e=>{e.preventDefault();msg(`La sección ${a.dataset.pagina} se creará después.`,"informacion")});cargar();
})();